// Pattern-wise sheet with verified LeetCode URLs (from uploaded Babua DSA Patterns PDF)
// Level: 1=Easy, 3=Medium, 5=Hard (native LeetCode tiers; unrated rows default to 3)
// Each problem: [title, level, url]  (url may be '' if none was given in the source)

const PATTERNS = [
{ name: "Two Pointers", resource: YT.striver, problems: [
  ["88. Merge Sorted Array",1,"https://leetcode.com/problems/merge-sorted-array/"],
  ["125. Valid Palindrome",1,"https://leetcode.com/problems/valid-palindrome/"],
  ["15. 3Sum",3,"https://leetcode.com/problems/3sum/"],
  ["19. Remove Nth Node From End of List",3,"https://leetcode.com/problems/remove-nth-node-from-end-of-list/"],
  ["75. Sort Colors",3,"https://leetcode.com/problems/sort-colors/"],
  ["151. Reverse Words in a String",3,"https://leetcode.com/problems/reverse-words-in-a-string/"],
  ["2193. Minimum Number of Moves to Make Palindrome",5,"https://leetcode.com/problems/minimum-number-of-moves-to-make-palindrome/"],
  ["2444. Count Subarrays With Fixed Bounds",5,"https://leetcode.com/problems/count-subarrays-with-fixed-bounds/"],
  ["1537. Get the Maximum Score",5,"https://leetcode.com/problems/get-the-maximum-score/"],
  ["321. Create Maximum Number",5,"https://leetcode.com/problems/create-maximum-number/"],
  ["Valid Word Abbreviation",3,"https://leetcode.com/problems/valid-word-abbreviation/description/"],
  ["Strobogrammatic Number",1,"https://leetcode.com/problems/strobogrammatic-number/description/"],
  ["Next Palindrome Using Same Digits",3,"https://leetcode.com/problems/next-palindrome-using-same-digits/description/"],
  ["Lowest Common Ancestor of a Binary Tree III",3,"https://neetcode.io/problems/lowest-common-ancestor-of-a-binary-tree-iii"],
  ["Find the Lexicographically Largest String From the Box II",3,"https://leetcode.com/problems/find-the-lexicographically-largest-string-from-the-boxii/description/"],
  ["2486. Append Characters to String to Make Subsequence",3,"https://leetcode.com/problems/append-characters-to-string-to-make-subsequence/"],
  ["977. Squares of a Sorted Array",1,"https://leetcode.com/problems/squares-of-a-sorted-array/"],
  ["344. Reverse String",1,"https://leetcode.com/problems/reverse-string/"],
  ["680. Valid Palindrome II",1,"https://leetcode.com/problems/valid-palindrome-ii/"],
  ["2824. Count Pairs Whose Sum is Less than Target",1,"https://leetcode.com/problems/count-pairs-whose-sum-is-less-than-target/description/"],
  ["1. Two Sum",1,"https://leetcode.com/problems/two-sum/description/"],
  ["167. Two Sum II - Input Array Is Sorted",3,"https://leetcode.com/problems/two-sum-ii-input-array-is-sorted/description/"],
  ["Sort Two Colors",3,""]
]},
{ name: "Fast and Slow Pointers", resource: YT.striver, problems: [
  ["202. Happy Number",1,"https://leetcode.com/problems/happy-number/"],
  ["141. Linked List Cycle",1,"https://leetcode.com/problems/linked-list-cycle/"],
  ["876. Middle of the Linked List",1,"https://leetcode.com/problems/middle-of-the-linked-list/"],
  ["457. Circular Array Loop",3,"https://leetcode.com/problems/circular-array-loop/"],
  ["287. Find the Duplicate Number",3,"https://leetcode.com/problems/find-the-duplicate-number/"],
  ["234. Palindrome Linked List",1,"https://leetcode.com/problems/palindrome-linked-list/"],
  ["2130. Maximum Twin Sum of a Linked List",3,"https://leetcode.com/problems/maximum-twin-sum-of-a-linked-list/"],
  ["Split a Circular Linked List",3,"https://leetcode.com/problems/split-a-circular-linked-list/description/"],
  ["142. Linked List Cycle II",3,"https://leetcode.com/problems/linked-list-cycle-ii/description/"],
  ["Find length of Loop",3,"https://www.geeksforgeeks.org/problems/find-length-of-loop/1"]
]},
{ name: "Heaps", resource: YT.striver, problems: [
  ["502. IPO",5,"https://leetcode.com/problems/ipo/"],
  ["295. Find Median from Data Stream",5,"https://leetcode.com/problems/find-median-from-data-stream/"],
  ["480. Sliding Window Median (BFA)",5,"https://leetcode.com/problems/sliding-window-median/"],
  ["621. Task Scheduler",3,"https://leetcode.com/problems/task-scheduler/"],
  ["2402. Meeting Rooms III",5,"https://leetcode.com/problems/meeting-rooms-iii/"],
  ["2231. Largest Number After Digit Swaps by Parity",1,"https://leetcode.com/problems/largest-number-after-digit-swaps-by-parity/"],
  ["436. Find Right Interval",3,"https://leetcode.com/problems/find-right-interval/"],
  ["Minimum Cost of Ropes",3,"https://www.geeksforgeeks.org/problems/minimum-cost-of-ropes-1587115620/1"],
  ["1405. Longest Happy String",3,"https://leetcode.com/problems/longest-happy-string/"],
  ["1792. Maximum Average Pass Ratio",3,"https://leetcode.com/problems/maximum-average-pass-ratio/"],
  ["1942. The Number of the Smallest Unoccupied Chair",3,"https://leetcode.com/problems/the-number-of-the-smallest-unoccupied-chair/"],
  ["1354. Construct Target Array With Multiple Sums",5,"https://leetcode.com/problems/construct-target-array-with-multiple-sums/"],
  ["1046. Last Stone Weight",1,"https://leetcode.com/problems/last-stone-weight/description/"],
  ["480. Sliding Window Median (Optimised)",5,"https://leetcode.com/problems/sliding-window-median/"]
]},
{ name: "Sliding Window", resource: YT.striver, problems: [
  ["187. Repeated DNA Sequences",3,"https://leetcode.com/problems/repeated-dna-sequences/"],
  ["239. Sliding Window Maximum",5,"https://leetcode.com/problems/sliding-window-maximum/"],
  ["Minimum Window Subsequence",3,"https://leetcode.com/problems/minimum-window-subsequence/description/"],
  ["424. Longest Repeating Character Replacement",3,"https://leetcode.com/problems/longest-repeating-character-replacement/"],
  ["76. Minimum Window Substring",5,"https://leetcode.com/problems/minimum-window-substring/"],
  ["3. Longest Substring Without Repeating Characters",3,"https://leetcode.com/problems/longest-substring-without-repeating-characters/"],
  ["209. Minimum Size Subarray Sum",3,"https://leetcode.com/problems/minimum-size-subarray-sum/"],
  ["643. Maximum Average Subarray I",1,"https://leetcode.com/problems/maximum-average-subarray-i/"],
  ["1343. Number of Sub-arrays of Size K and Average ≥ Threshold",3,"https://leetcode.com/problems/number-of-sub-arrays-of-size-k-and-average-greater-than-or-equal-to-threshold/description/"],
  ["904. Fruit Into Baskets",3,"https://leetcode.com/problems/fruit-into-baskets/"],
  ["219. Contains Duplicate II",1,"https://leetcode.com/problems/contains-duplicate-ii/"],
  ["1838. Frequency of the Most Frequent Element",3,"https://leetcode.com/problems/frequency-of-the-most-frequent-element/"],
  ["992. Subarrays with K Different Integers",5,"https://leetcode.com/problems/subarrays-with-k-different-integers/"],
  ["2302. Count Subarrays With Score Less Than K",5,"https://leetcode.com/problems/count-subarrays-with-score-less-than-k/"],
  ["Count Substrings With K-Frequency Characters II",3,"https://leetcode.com/problems/count-substrings-with-k-frequency-characters-ii/description/"],
  ["2461. Maximum Sum of Distinct Subarrays With Length K",3,"https://leetcode.com/problems/maximum-sum-of-distinct-subarrays-with-length-k/description/"],
  ["Max Sum Subarray of size K",3,"https://www.geeksforgeeks.org/problems/max-sum-subarray-of-size-k5313/1"],
  ["Rabin Karp Algorithm",3,"https://leetcode.com/problems/repeated-dna-sequences/"],
  ["3. Longest Substring Without Repeating Characters (Map Approach)",5,"https://leetcode.com/problems/longest-substring-without-repeating-characters/"]
]},
{ name: "Intervals", resource: YT.striver, problems: [
  ["56. Merge Intervals",3,"https://leetcode.com/problems/merge-intervals/"],
  ["57. Insert Interval",3,"https://leetcode.com/problems/insert-interval/"],
  ["986. Interval List Intersections",3,"https://leetcode.com/problems/interval-list-intersections/"],
  ["Employee Free Time",3,"https://leetcode.com/problems/employee-free-time/description/"],
  ["3169. Count Days Without Meetings (Approach 1)",3,"https://leetcode.com/problems/count-days-without-meetings/"],
  ["1288. Remove Covered Intervals",3,"https://leetcode.com/problems/remove-covered-intervals/"],
  ["1094. Car Pooling",3,"https://leetcode.com/problems/car-pooling/"],
  ["352. Data Stream as Disjoint Intervals (Brute Force + TreeSet)",5,"https://leetcode.com/problems/data-stream-as-disjoint-intervals/"],
  ["Meeting Rooms II (Line Sweep)",3,"https://www.geeksforgeeks.org/problems/attend-all-meetings-ii/1"],
  ["56. Merge Intervals (Brute Force)",3,"https://leetcode.com/problems/merge-intervals/"],
  ["3169. Count Days Without Meetings (Approach 2)",3,"https://leetcode.com/problems/count-days-without-meetings/"],
  ["3169. Count Days Without Meetings (Approach 3)",3,"https://leetcode.com/problems/count-days-without-meetings/"],
  ["Line Sweep Algorithm (Theory)",3,""],
  ["TreeMap + Lab (Theory)",3,""],
  ["731. My Calendar II",3,"https://leetcode.com/problems/my-calendar-ii/description/"],
  ["Meeting Rooms",1,"https://www.geeksforgeeks.org/problems/attend-all-meetings/1"],
  ["729. My Calendar I (Brute Force + Line Sweep)",3,"https://leetcode.com/problems/my-calendar-i/description/"],
  ["732. My Calendar III (Line Sweep)",5,"https://leetcode.com/problems/my-calendar-iii/description/"],
  ["729. My Calendar I (Optimised)",3,"https://leetcode.com/problems/my-calendar-i/description/"],
  ["Meeting Rooms II (Heap)",3,"https://www.geeksforgeeks.org/problems/attend-all-meetings-ii/1"],
  ["Meeting Rooms II (Two Pointer)",3,"https://www.geeksforgeeks.org/problems/attend-all-meetings-ii/1"],
  ["352. Data Stream as Disjoint Intervals (TreeMap)",5,"https://leetcode.com/problems/data-stream-as-disjoint-intervals/"]
]},
{ name: "Linked List: In-Place Manipulation", resource: YT.striver, problems: [
  ["206. Reverse Linked List",1,"https://leetcode.com/problems/reverse-linked-list/"],
  ["25. Reverse Nodes in k-Group",5,"https://leetcode.com/problems/reverse-nodes-in-k-group/"],
  ["92. Reverse Linked List II",3,"https://leetcode.com/problems/reverse-linked-list-ii/"],
  ["143. Reorder List",3,"https://leetcode.com/problems/reorder-list/"],
  ["1721. Swapping Nodes in a Linked List",3,"https://leetcode.com/problems/swapping-nodes-in-a-linked-list/"],
  ["2074. Reverse Nodes in Even Length Groups",3,"https://leetcode.com/problems/reverse-nodes-in-even-length-groups/"],
  ["83. Remove Duplicates from Sorted List",1,"https://leetcode.com/problems/remove-duplicates-from-sorted-list/"],
  ["203. Remove Linked List Elements",1,"https://leetcode.com/problems/remove-linked-list-elements/"],
  ["725. Split Linked List in Parts",3,"https://leetcode.com/problems/split-linked-list-in-parts/"],
  ["Delete N Nodes After M Nodes of a Linked List",3,"https://leetcode.com/problems/delete-n-nodes-after-m-nodes-of-a-linked-list/description/"],
  ["Insert into a Sorted Circular Linked List",3,"https://neetcode.io/problems/insert-into-a-sorted-circular-linked-list/question"],
  ["328. Odd Even Linked List",3,"https://leetcode.com/problems/odd-even-linked-list/"],
  ["24. Swap Nodes in Pairs",3,"https://leetcode.com/problems/swap-nodes-in-pairs/description/"],
  ["Dummy Node Concept (Theory)",3,""]
]},
{ name: "K-way Merge", resource: YT.coderArmy, problems: [
  ["88. Merge Sorted Array",1,"https://leetcode.com/problems/merge-sorted-array/"],
  ["1439. Find the Kth Smallest Sum of a Matrix With Sorted Rows",5,"https://leetcode.com/problems/find-the-kth-smallest-sum-of-a-matrix-with-sorted-rows/description/"],
  ["373. Find K Pairs with Smallest Sums",3,"https://leetcode.com/problems/find-k-pairs-with-smallest-sums/"],
  ["23. Merge k Sorted Lists",5,"https://leetcode.com/problems/merge-k-sorted-lists/"],
  ["Kth Smallest Element in a Sorted Matrix",3,"https://leetcode.com/problems/kth-smallest-element-in-a-sorted-matrix/"],
  ["786. K-th Smallest Prime Fraction",3,"https://leetcode.com/problems/k-th-smallest-prime-fraction/"],
  ["313. Super Ugly Number",3,"https://leetcode.com/problems/super-ugly-number/"],
  ["Find m-th smallest value in k sorted arrays",3,"https://www.geeksforgeeks.org/dsa/find-m-th-smallest-value-in-k-sorted-arrays/"],
  ["21. Merge Two Sorted Lists",1,"https://leetcode.com/problems/merge-two-sorted-lists/description/"]
]},
{ name: "Top K Elements", resource: YT.striver, problems: [
  ["703. Kth Largest Element in a Stream",1,"https://leetcode.com/problems/kth-largest-element-in-a-stream/"],
  ["767. Reorganize String",3,"https://leetcode.com/problems/reorganize-string/"],
  ["973. K Closest Points to Origin",3,"https://leetcode.com/problems/k-closest-points-to-origin/"],
  ["347. Top K Frequent Elements",3,"https://leetcode.com/problems/top-k-frequent-elements/"],
  ["215. Kth Largest Element in an Array",3,"https://leetcode.com/problems/kth-largest-element-in-an-array/"],
  ["414. Third Maximum Number",1,"https://leetcode.com/problems/third-maximum-number/"],
  ["2099. Find Subsequence of Length K With the Largest Sum",1,"https://leetcode.com/problems/find-subsequence-of-length-k-with-the-largest-sum/"],
  ["857. Minimum Cost to Hire K Workers",5,"https://leetcode.com/problems/minimum-cost-to-hire-k-workers/"],
  ["2530. Maximal Score After Applying K Operations",3,"https://leetcode.com/problems/maximal-score-after-applying-k-operations/"],
  ["1985. Find the Kth Largest Integer in the Array",3,"https://leetcode.com/problems/find-the-kth-largest-integer-in-the-array/"],
  ["1383. Maximum Performance of a Team",5,"https://leetcode.com/problems/maximum-performance-of-a-team/"],
  ["632. Smallest Range Covering Elements from K Lists",5,"https://leetcode.com/problems/smallest-range-covering-elements-from-k-lists/"],
  ["683. K Empty Slots",5,"https://leetcode.com/problems/k-empty-slots/"],
  ["3478. Choose K Elements With Maximum Sum",3,"https://leetcode.com/problems/choose-k-elements-with-maximum-sum/description/"],
  ["2233. Maximum Product After K Increments",3,"https://leetcode.com/problems/maximum-product-after-k-increments/"],
  ["2386. Find the K-Sum of an Array",5,"https://leetcode.com/problems/find-the-k-sum-of-an-array/"],
  ["1481. Least Number of Unique Integers after K Removals",3,"https://leetcode.com/problems/least-number-of-unique-integers-after-k-removals/"],
  ["3264. Final Array State After K Multiplication Operations I",1,"https://leetcode.com/problems/final-array-state-after-k-multiplication-operations-i/"],
  ["3266. Final Array State After K Multiplication Operations II",5,"https://leetcode.com/problems/final-array-state-after-k-multiplication-operations-ii/description/"]
]},
{ name: "Binary Search", resource: YT.striver, problems: [
  ["704. Binary Search",1,"https://leetcode.com/problems/binary-search/description/"],
  ["33. Search in Rotated Sorted Array",3,"https://leetcode.com/problems/search-in-rotated-sorted-array/description/"],
  ["278. First Bad Version",1,"https://leetcode.com/problems/first-bad-version/"],
  ["528. Random Pick with Weight",3,"https://leetcode.com/problems/random-pick-with-weight/"],
  ["658. Find K Closest Elements",3,"https://leetcode.com/problems/find-k-closest-elements/"],
  ["540. Single Element in a Sorted Array",3,"https://leetcode.com/problems/single-element-in-a-sorted-array/"],
  ["1802. Maximum Value at a Given Index in a Bounded Array",3,"https://leetcode.com/problems/maximum-value-at-a-given-index-in-a-bounded-array/"],
  ["1337. The K Weakest Rows in a Matrix",1,"https://leetcode.com/problems/the-k-weakest-rows-in-a-matrix/"],
  ["410. Split Array Largest Sum",5,"https://leetcode.com/problems/split-array-largest-sum/"],
  ["154. Find Minimum in Rotated Sorted Array II",5,"https://leetcode.com/problems/find-minimum-in-rotated-sorted-array-ii/"],
  ["2141. Maximum Running Time of N Computers",5,"https://leetcode.com/problems/maximum-running-time-of-n-computers/description/"],
  ["774. Minimize Max Distance to Gas Station",5,"https://leetcode.com/problems/minimize-max-distance-to-gas-station/"],
  ["1231. Divide Chocolate",5,"https://leetcode.com/problems/divide-chocolate/"],
  ["2035. Partition Array Into Two Arrays to Minimize Sum Difference",5,"https://leetcode.com/problems/partition-array-into-two-arrays-to-minimize-sum-difference/description/"],
  ["2251. Number of Flowers in Full Bloom",5,"https://leetcode.com/problems/number-of-flowers-in-full-bloom/description/"],
  ["875. Koko Eating Bananas",3,"https://leetcode.com/problems/koko-eating-bananas/description/"],
  ["81. Search in Rotated Sorted Array II",3,"https://leetcode.com/problems/search-in-rotated-sorted-array-ii/description/"],
  ["162. Find Peak Element",3,"https://leetcode.com/problems/find-peak-element/description/"],
  ["34. Find First and Last Position of Element in Sorted Array",3,"https://leetcode.com/problems/find-first-and-last-position-of-element-in-sorted-array/description/"],
  ["69. Sqrt(x)",3,"https://leetcode.com/problems/sqrtx/description/"],
  ["153. Find Minimum in Rotated Sorted Array",3,"https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/description/"],
  ["540. Single Element in a Sorted Array (Linear to Binary Approach)",3,"https://leetcode.com/problems/single-element-in-a-sorted-array/"],
  ["1337. The K Weakest Rows in a Matrix (Heap Approach)",1,"https://leetcode.com/problems/the-k-weakest-rows-in-a-matrix/"],
  ["658. Find K Closest Elements (mid→mid+k Approach)",3,"https://leetcode.com/problems/find-k-closest-elements/"],
  ["Binary Search on Answer (Theory)",3,""]
]},
{ name: "Cyclic Sort", resource: YT.coderArmy, problems: [
  ["Cyclic Sort (Theory)",3,""],
  ["268. Missing Number",1,"https://leetcode.com/problems/missing-number/"],
  ["41. First Missing Positive",5,"https://leetcode.com/problems/first-missing-positive/"],
  ["645. Set Mismatch",1,"https://leetcode.com/problems/set-mismatch/"],
  ["448. Find All Numbers Disappeared in an Array",1,"https://leetcode.com/problems/find-all-numbers-disappeared-in-an-array/"],
  ["287. Find the Duplicate Number",3,"https://leetcode.com/problems/find-the-duplicate-number/description/"]
]},
{ name: "Subsets", resource: YT.adityaVerma, problems: [
  ["78. Subsets",3,"https://leetcode.com/problems/subsets/"],
  ["46. Permutations",3,"https://leetcode.com/problems/permutations/"],
  ["17. Letter Combinations of a Phone Number",3,"https://leetcode.com/problems/letter-combinations-of-a-phone-number/"],
  ["22. Generate Parentheses",3,"https://leetcode.com/problems/generate-parentheses/"],
  ["784. Letter Case Permutation",3,"https://leetcode.com/problems/letter-case-permutation/"],
  ["1079. Letter Tile Possibilities",3,"https://leetcode.com/problems/letter-tile-possibilities/"],
  ["698. Partition to K Equal Sum Subsets",3,"https://leetcode.com/problems/partition-to-k-equal-sum-subsets/"],
  ["2035. Partition Array Into Two Arrays to Minimize Sum Difference",5,"https://leetcode.com/problems/partition-array-into-two-arrays-to-minimize-sum-difference/description/"],
  ["90. Subsets II",3,"https://leetcode.com/problems/subsets-ii/description/"],
  ["47. Permutations II",3,"https://leetcode.com/problems/permutations-ii/description/"],
  ["3437. Permutations III",3,"https://leetcode.com/problems/permutations-iii/description/"],
  ["3470. Permutations IV",5,"https://leetcode.com/problems/permutations-iv/description/"]
]},
{ name: "Greedy Programming", resource: YT.striver, problems: [
  ["670. Maximum Swap",3,"https://leetcode.com/problems/maximum-swap/"],
  ["605. Can Place Flowers",1,"https://leetcode.com/problems/can-place-flowers/"],
  ["1903. Largest Odd Number in String",1,"https://leetcode.com/problems/largest-odd-number-in-string/"],
  ["135. Candy",5,"https://leetcode.com/problems/candy/description/"],
  ["2366. Minimum Replacements to Sort the Array",5,"https://leetcode.com/problems/minimum-replacements-to-sort-the-array/"],
  ["45. Jump Game II",3,"https://leetcode.com/problems/jump-game-ii/"],
  ["121. Best Time to Buy and Sell Stock",1,"https://leetcode.com/problems/best-time-to-buy-and-sell-stock/"],
  ["55. Jump Game",3,"https://leetcode.com/problems/jump-game/description/"],
  ["881. Boats to Save People",3,"https://leetcode.com/problems/boats-to-save-people/description/"],
  ["134. Gas Station",3,"https://leetcode.com/problems/gas-station/description/"],
  ["1029. Two City Scheduling",3,"https://leetcode.com/problems/two-city-scheduling/description/"],
  ["871. Minimum Number of Refueling Stops",5,"https://leetcode.com/problems/minimum-number-of-refueling-stops/description/"],
  ["122. Best Time to Buy and Sell Stock II",3,"https://leetcode.com/problems/best-time-to-buy-and-sell-stock-ii/description/"]
]},
{ name: "Backtracking", resource: YT.adityaVerma, problems: [
  ["52. N-Queens II",5,"https://leetcode.com/problems/n-queens-ii/"],
  ["79. Word Search",3,"https://leetcode.com/problems/word-search/"],
  ["337. House Robber III",3,"https://leetcode.com/problems/house-robber-iii/"],
  ["93. Restore IP Addresses",3,"https://leetcode.com/problems/restore-ip-addresses/"],
  ["733. Flood Fill",1,"https://leetcode.com/problems/flood-fill/"],
  ["2850. Minimum Moves to Spread Stones Over Grid",3,"https://leetcode.com/problems/minimum-moves-to-spread-stones-over-grid/"],
  ["257. Binary Tree Paths",1,"https://leetcode.com/problems/binary-tree-paths/"],
  ["401. Binary Watch",1,"https://leetcode.com/problems/binary-watch/"],
  ["465. Optimal Account Balancing",5,"https://leetcode.com/problems/optimal-account-balancing/"],
  ["1593. Split a String Into the Max Number of Unique Substrings",3,"https://leetcode.com/problems/split-a-string-into-the-max-number-of-unique-substrings/"],
  ["797. All Paths From Source to Target",3,"https://leetcode.com/problems/all-paths-from-source-to-target/"],
  ["301. Remove Invalid Parentheses",5,"https://leetcode.com/problems/remove-invalid-parentheses/"],
  ["51. N-Queens",5,"https://leetcode.com/problems/n-queens/"],
  ["980. Unique Paths III",5,"https://leetcode.com/problems/unique-paths-iii/"],
  ["77. Combinations",3,"https://leetcode.com/problems/combinations/"],
  ["37. Sudoku Solver",5,"https://leetcode.com/problems/sudoku-solver/"],
  ["473. Matchsticks to Square",3,"https://leetcode.com/problems/matchsticks-to-square/"]
]},
{ name: "Dynamic Programming", resource: YT.adityaVerma, problems: [
  ["416. Partition Equal Subset Sum",3,"https://leetcode.com/problems/partition-equal-subset-sum/"],
  ["322. Coin Change",3,"https://leetcode.com/problems/coin-change/"],
  ["1137. N-th Tribonacci Number",1,"https://leetcode.com/problems/n-th-tribonacci-number/"],
  ["338. Counting Bits",1,"https://leetcode.com/problems/counting-bits/"],
  ["542. 01 Matrix",3,"https://leetcode.com/problems/01-matrix/"],
  ["213. House Robber II",3,"https://leetcode.com/problems/house-robber-ii/"],
  ["152. Maximum Product Subarray",3,"https://leetcode.com/problems/maximum-product-subarray/"],
  ["39. Combination Sum",3,"https://leetcode.com/problems/combination-sum/"],
  ["139. Word Break",3,"https://leetcode.com/problems/word-break/"],
  ["647. Palindromic Substrings",3,"https://leetcode.com/problems/palindromic-substrings/"],
  ["1143. Longest Common Subsequence",3,"https://leetcode.com/problems/longest-common-subsequence/"],
  ["140. Word Break II",5,"https://leetcode.com/problems/word-break-ii/"],
  ["91. Decode Ways",3,"https://leetcode.com/problems/decode-ways/"],
  ["1987. Count the Number of Good Subsequences",5,"https://leetcode.com/problems/number-of-unique-good-subsequences/"],
  ["968. Binary Tree Cameras",5,"https://leetcode.com/problems/binary-tree-cameras/"],
  ["1639. Number of Ways to Form Target String Given a Dictionary",5,"https://leetcode.com/problems/number-of-ways-to-form-a-target-string-given-a-dictionary/"],
  ["118. Pascal's Triangle",1,"https://leetcode.com/problems/pascals-triangle/"],
  ["120. Triangle",3,"https://leetcode.com/problems/triangle/"],
  ["70. Climbing Stairs",1,"https://leetcode.com/problems/climbing-stairs/"]
]},
{ name: "Topological Sort", resource: YT.striver, problems: [
  ["Compilation Order (~210 Course Schedule II)",3,"https://leetcode.com/problems/course-schedule-ii/"],
  ["269. Alien Dictionary",5,"https://leetcode.com/problems/alien-dictionary/"],
  ["953. Verifying an Alien Dictionary",1,"https://leetcode.com/problems/verifying-an-alien-dictionary/"],
  ["210. Course Schedule II",3,"https://leetcode.com/problems/course-schedule-ii/"],
  ["207. Course Schedule",3,"https://leetcode.com/problems/course-schedule/"],
  ["2392. Build a Matrix with Conditions",5,"https://leetcode.com/problems/build-a-matrix-with-conditions/"],
  ["2246. Longest Path With Different Adjacent Characters",5,"https://leetcode.com/problems/longest-path-with-different-adjacent-characters/"],
  ["2050. Parallel Courses III",5,"https://leetcode.com/problems/parallel-courses-iii/"],
  ["2115. Find All Possible Recipes from Given Supplies",3,"https://leetcode.com/problems/find-all-possible-recipes-from-given-supplies/"]
]},
{ name: "Sort and Search", resource: YT.coderArmy, problems: [
  ["1385. Find the Distance Value Between Two Arrays",1,"https://leetcode.com/problems/find-the-distance-value-between-two-arrays/"],
  ["2389. Longest Subsequence With Limited Sum",1,"https://leetcode.com/problems/longest-subsequence-with-limited-sum/"],
  ["2089. Find Target Indices After Sorting Array",1,"https://leetcode.com/problems/find-target-indices-after-sorting-array/"],
  ["1537. Count Pairs in Two Arrays",5,"https://leetcode.com/problems/count-pairs-in-two-arrays/"],
  ["611. Valid Triangle Number",3,"https://leetcode.com/problems/valid-triangle-number/"],
  ["2602. Minimum Operations to Make All Array Elements Equal",3,"https://leetcode.com/problems/minimum-operations-to-make-all-array-elements-equal/"],
  ["1300. Sum of Mutated Array Closest to Target",3,"https://leetcode.com/problems/sum-of-mutated-array-closest-to-target/"],
  ["1508. Range Sum of Sorted Subarray Sums",3,"https://leetcode.com/problems/range-sum-of-sorted-subarray-sums/"],
  ["1552. Magnetic Force Between Two Balls",3,"https://leetcode.com/problems/magnetic-force-between-two-balls/"],
  ["719. Find K-th Smallest Pair Distance",5,"https://leetcode.com/problems/find-k-th-smallest-pair-distance/"],
  ["1889. Minimum Space Wasted from Packaging",5,"https://leetcode.com/problems/minimum-space-wasted-from-packaging/"],
  ["354. Russian Doll Envelopes",5,"https://leetcode.com/problems/russian-doll-envelopes/"],
  ["2551. Put Marbles in Bags",5,"https://leetcode.com/problems/put-marbles-in-bags/"],
  ["274. H-Index",3,"https://leetcode.com/problems/h-index/"],
  ["1099. Two Sum Less Than K",1,"https://leetcode.com/problems/two-sum-less-than-k/"],
  ["2554. Maximum Number of Integers to Choose from a Range I",3,"https://leetcode.com/problems/maximum-number-of-integers-to-choose-from-a-range-i/"]
]},
{ name: "Matrices", resource: YT.striver, problems: [
  ["73. Set Matrix Zeroes",3,"https://leetcode.com/problems/set-matrix-zeroes/"],
  ["48. Rotate Image",3,"https://leetcode.com/problems/rotate-image/"],
  ["54. Spiral Matrix",3,"https://leetcode.com/problems/spiral-matrix/"],
  ["1706. Where Will the Ball Fall",3,"https://leetcode.com/problems/where-will-the-ball-fall/"],
  ["867. Transpose Matrix",1,"https://leetcode.com/problems/transpose-matrix/"],
  ["1351. Count Negative Numbers in a Sorted Matrix",1,"https://leetcode.com/problems/count-negative-numbers-in-a-sorted-matrix/"],
  ["2812. Minimum Time Takes to Reach Destination Without Drowning",5,"https://leetcode.com/problems/find-the-safest-path-in-a-grid/"],
  ["302. Smallest Rectangle Enclosing Black Pixels",5,"https://leetcode.com/problems/smallest-rectangle-enclosing-black-pixels/"],
  ["463. Island Perimeter",1,"https://leetcode.com/problems/island-perimeter/"],
  ["2022. Convert 1D Array Into 2D Array",1,"https://leetcode.com/problems/convert-1d-array-into-2d-array/"],
  ["59. Spiral Matrix II",3,"https://leetcode.com/problems/spiral-matrix-ii/"],
  ["1072. Flip Columns For Maximum Number of Equal Rows",3,"https://leetcode.com/problems/flip-columns-for-maximum-number-of-equal-rows/"],
  ["2061. Number of Spaces Cleaning Robot Cleaned",3,"https://leetcode.com/problems/number-of-spaces-cleaning-robot-cleaned/"],
  ["Minimize Maximum Value in a Grid (~2537)",5,"https://leetcode.com/problems/minimum-operations-to-make-array-equal-ii/"],
  ["668. Kth Smallest Number in Multiplication Table",5,"https://leetcode.com/problems/kth-smallest-number-in-multiplication-table/"],
  ["778. Swim in Rising Water",5,"https://leetcode.com/problems/swim-in-rising-water/"],
  ["296. Best Meeting Point",5,"https://leetcode.com/problems/best-meeting-point/"],
  ["289. Game of Life",3,"https://leetcode.com/problems/game-of-life/"]
]},
{ name: "Stacks", resource: YT.striver, problems: [
  ["224. Basic Calculator",5,"https://leetcode.com/problems/basic-calculator/"],
  ["1047. Remove All Adjacent Duplicates In String",1,"https://leetcode.com/problems/remove-all-adjacent-duplicates-in-string/"],
  ["1249. Minimum Remove to Make Valid Parentheses",3,"https://leetcode.com/problems/minimum-remove-to-make-valid-parentheses/"],
  ["636. Exclusive Time of Functions",3,"https://leetcode.com/problems/exclusive-time-of-functions/"],
  ["341. Flatten Nested List Iterator",3,"https://leetcode.com/problems/flatten-nested-list-iterator/"],
  ["232. Implement Queue Using Stacks",1,"https://leetcode.com/problems/implement-queue-using-stacks/"],
  ["739. Daily Temperatures",3,"https://leetcode.com/problems/daily-temperatures/"],
  ["394. Decode String",3,"https://leetcode.com/problems/decode-string/"],
  ["2696. Minimum String Length After Removing Substrings",1,"https://leetcode.com/problems/minimum-string-length-after-removing-substrings/"],
  ["1063. Number of Valid Subarrays",5,"https://leetcode.com/problems/number-of-valid-subarrays/"],
  ["1944. Number of Visible People in a Queue",5,"https://leetcode.com/problems/number-of-visible-people-in-a-queue/"],
  ["1106. Parsing a Boolean Expression",5,"https://leetcode.com/problems/parsing-a-boolean-expression/"],
  ["316. Remove Duplicate Letters",3,"https://leetcode.com/problems/remove-duplicate-letters/"],
  ["20. Valid Parentheses",1,"https://leetcode.com/problems/valid-parentheses/"],
  ["32. Longest Valid Parentheses",5,"https://leetcode.com/problems/longest-valid-parentheses/description/"],
  ["962. Maximum Width Ramp",3,"https://leetcode.com/problems/maximum-width-ramp/description/"],
  ["496. Next Greater Element I",3,"https://leetcode.com/problems/next-greater-element-i/description/"],
  ["503. Next Greater Element II",3,"https://leetcode.com/problems/next-greater-element-ii/description/"],
  ["556. Next Greater Element III",3,"https://leetcode.com/problems/next-greater-element-iii/description/"],
  ["2454. Next Greater Element IV",5,"https://leetcode.com/problems/next-greater-element-iv/description/"],
  ["Next Greater Elements",3,""],
  ["Next Smaller Elements",3,""],
  ["Prev Greater Elements",3,""],
  ["Prev Smaller Elements",3,""]
]},
{ name: "Graphs", resource: YT.striver, problems: [
  ["743. Network Delay Time",3,"https://leetcode.com/problems/network-delay-time/"],
  ["1971. Paths in Maze That Lead to Same Room",1,"https://leetcode.com/problems/find-if-path-exists-in-graph/"],
  ["133. Clone Graph",3,"https://leetcode.com/problems/clone-graph/"],
  ["261. Graph Valid Tree",3,"https://leetcode.com/problems/graph-valid-tree/"],
  ["815. Bus Routes",5,"https://leetcode.com/problems/bus-routes/"],
  ["332. Reconstruct Itinerary",5,"https://leetcode.com/problems/reconstruct-itinerary/"],
  ["997. Find the Town Judge",1,"https://leetcode.com/problems/find-the-town-judge/"],
  ["1791. Find Center of Star Graph",1,"https://leetcode.com/problems/find-center-of-star-graph/"],
  ["1380. Lucky Numbers in a Matrix",1,"https://leetcode.com/problems/lucky-numbers-in-a-matrix/"],
  ["1514. Path with Maximum Probability",3,"https://leetcode.com/problems/path-with-maximum-probability/"],
  ["1245. Tree Diameter",3,"https://leetcode.com/problems/tree-diameter/"],
  ["1466. Reorder Routes to Make All Paths Lead to the City Zero",3,"https://leetcode.com/problems/reorder-routes-to-make-all-paths-lead-to-the-city-zero/"],
  ["1368. Minimum Cost to Make at Least One Valid Path in a Grid",5,"https://leetcode.com/problems/minimum-cost-to-make-at-least-one-valid-path-in-a-grid/"],
  ["2360. Longest Cycle in a Graph",5,"https://leetcode.com/problems/longest-cycle-in-a-graph/"],
  ["2608. Shortest Cycle in a Graph",5,"https://leetcode.com/problems/shortest-cycle-in-a-graph/"]
]},
{ name: "Tree Depth-First Search", resource: YT.striver, problems: [
  ["114. Flatten Binary Tree to Linked List",3,"https://leetcode.com/problems/flatten-binary-tree-to-linked-list/"],
  ["543. Diameter of Binary Tree",1,"https://leetcode.com/problems/diameter-of-binary-tree/"],
  ["297. Serialize and Deserialize Binary Tree",5,"https://leetcode.com/problems/serialize-and-deserialize-binary-tree/"],
  ["226. Invert Binary Tree",1,"https://leetcode.com/problems/invert-binary-tree/"],
  ["124. Binary Tree Maximum Path Sum",5,"https://leetcode.com/problems/binary-tree-maximum-path-sum/"],
  ["108. Convert Sorted Array to Binary Search Tree",1,"https://leetcode.com/problems/convert-sorted-array-to-binary-search-tree/"],
  ["105. Build Binary Tree from Preorder and Inorder Traversal",3,"https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal/"],
  ["199. Binary Tree Right Side View",3,"https://leetcode.com/problems/binary-tree-right-side-view/"],
  ["236. Lowest Common Ancestor of a Binary Tree",3,"https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-tree/"],
  ["98. Validate Binary Search Tree",3,"https://leetcode.com/problems/validate-binary-search-tree/"],
  ["364. Nested List Weight Sum II",3,"https://leetcode.com/problems/nested-list-weight-sum-ii/"],
  ["285. Inorder Successor in BST",3,"https://leetcode.com/problems/inorder-successor-in-bst/"],
  ["2458. Height of Binary Tree After Subtree Removal Queries",5,"https://leetcode.com/problems/height-of-binary-tree-after-subtree-removal-queries/"],
  ["1110. Delete Nodes And Return Forest",3,"https://leetcode.com/problems/delete-nodes-and-return-forest/"],
  ["834. Sum of Distances in a Tree",5,"https://leetcode.com/problems/sum-of-distances-in-tree/"],
  ["1028. Recover a Tree From Preorder Traversal",5,"https://leetcode.com/problems/recover-a-tree-from-preorder-traversal/"],
  ["104. Maximum Depth of Binary Tree",1,"https://leetcode.com/problems/maximum-depth-of-binary-tree/"],
  ["230. Kth Smallest Element in a BST",3,"https://leetcode.com/problems/kth-smallest-element-in-a-bst/"]
]},
{ name: "Tree Breadth-First Search", resource: YT.striver, problems: [
  ["102. Binary Tree Level Order Traversal",3,"https://leetcode.com/problems/binary-tree-level-order-traversal/"],
  ["103. Binary Tree Zigzag Level Order Traversal",3,"https://leetcode.com/problems/binary-tree-zigzag-level-order-traversal/"],
  ["116. Populating Next Right Pointers in Each Node",3,"https://leetcode.com/problems/populating-next-right-pointers-in-each-node/"],
  ["987. Vertical Order Traversal of a Binary Tree",5,"https://leetcode.com/problems/vertical-order-traversal-of-a-binary-tree/"],
  ["101. Symmetric Tree",1,"https://leetcode.com/problems/symmetric-tree/"],
  ["127. Word Ladder",5,"https://leetcode.com/problems/word-ladder/"],
  ["653. Two Sum IV - Input Is a BST",1,"https://leetcode.com/problems/two-sum-iv-input-is-a-bst/"],
  ["3203. Find Minimum Diameter After Merging Two Trees",5,"https://leetcode.com/problems/find-minimum-diameter-after-merging-two-trees/"],
  ["3169. Closest Node to Path in Tree",5,"https://leetcode.com/problems/closest-node-to-path-in-tree/"],
  ["1377. Frog Position After T Seconds",5,"https://leetcode.com/problems/frog-position-after-t-seconds/"],
  ["637. Average of Levels in Binary Tree",1,"https://leetcode.com/problems/average-of-levels-in-binary-tree/"],
  ["Connect All Siblings of a Binary Tree (~117)",3,"https://leetcode.com/problems/populating-next-right-pointers-in-each-node-ii/"]
]},
{ name: "Trie", resource: YT.kunal, problems: [
  ["208. Implement Trie (Prefix Tree)",3,"https://leetcode.com/problems/implement-trie-prefix-tree/"],
  ["1268. Search Suggestions System",3,"https://leetcode.com/problems/search-suggestions-system/description/"],
  ["648. Replace Words",3,"https://leetcode.com/problems/replace-words/description/"],
  ["211. Design Add and Search Words Data Structure",3,"https://leetcode.com/problems/design-add-and-search-words-data-structure/description/"],
  ["212. Word Search II",5,"https://leetcode.com/problems/word-search-ii/description/"],
  ["692. Top K Frequent Words",3,"https://leetcode.com/problems/top-k-frequent-words/description/"],
  ["14. Longest Common Prefix",1,"https://leetcode.com/problems/longest-common-prefix/description/"],
  ["1065. Index Pairs of a String",1,"https://leetcode.com/problems/index-pairs-of-a-string/description/"],
  ["440. K-th Smallest in Lexicographical Order",5,"https://leetcode.com/problems/k-th-smallest-in-lexicographical-order/description/"],
  ["336. Palindrome Pairs",5,"https://leetcode.com/problems/palindrome-pairs/description/"],
  ["3093. Longest Common Suffix Queries",5,"https://leetcode.com/problems/longest-common-suffix-queries/description/"],
  ["677. Map Sum Pairs",3,"https://leetcode.com/problems/map-sum-pairs/description/"],
  ["1455. Check If a Word Occurs As a Prefix of Any Word in a Sentence",1,"https://leetcode.com/problems/check-if-a-word-occurs-as-a-prefix-of-any-word-in-asentence/description/"],
  ["1858. Longest Word With All Prefixes",3,"https://leetcode.com/problems/longest-word-with-all-prefixes/description/"],
  ["386. Lexicographical Numbers",3,"https://leetcode.com/problems/lexicographical-numbers/description/"]
]},
{ name: "HashMaps", resource: YT.striver, problems: [
  ["706. Design HashMap",1,"https://leetcode.com/problems/design-hashmap/description/"],
  ["166. Fraction to Recurring Decimal",3,"https://leetcode.com/problems/fraction-to-recurring-decimal/description/"],
  ["359. Logger Rate Limiter",1,"https://leetcode.com/problems/logger-rate-limiter/description/"],
  ["496. Next Greater Element I",1,"https://leetcode.com/problems/next-greater-element-i/description/"],
  ["205. Isomorphic Strings",1,"https://leetcode.com/problems/isomorphic-strings/description/"],
  ["609. Find Duplicate File in System",3,"https://leetcode.com/problems/find-duplicate-file-in-system/description/"],
  ["1086. High Five",1,"https://leetcode.com/problems/high-five/description/"],
  ["299. Bulls and Cows",3,"https://leetcode.com/problems/bulls-and-cows/description/"],
  ["791. Custom Sort String",3,"https://leetcode.com/problems/custom-sort-string/description/"],
  ["694. Number of Distinct Islands",3,"https://leetcode.com/problems/number-of-distinct-islands/description/"],
  ["1915. Number of Wonderful Substrings",3,"https://leetcode.com/problems/number-of-wonderful-substrings/description/"],
  ["2262. Total Appeal of A String",5,"https://leetcode.com/problems/total-appeal-of-a-string/description/"],
  ["523. Continuous Subarray Sum",3,"https://leetcode.com/problems/continuous-subarray-sum/description/"],
  ["1207. Unique Number of Occurrences",1,"https://leetcode.com/problems/unique-number-of-occurrences/description/"],
  ["1392. Longest Happy Prefix",5,"https://leetcode.com/problems/longest-happy-prefix/description/"],
  ["3104. Find Longest Self-Contained Substring",5,"https://leetcode.com/problems/find-longest-self-contained-substring/description/"],
  ["349. Intersection of Two Arrays",1,"https://leetcode.com/problems/intersection-of-two-arrays/description/"],
  ["290. Word Pattern",1,"https://leetcode.com/problems/word-pattern/description/"],
  ["409. Longest Palindrome",1,"https://leetcode.com/problems/longest-palindrome/description/"]
]},
{ name: "Union Find", resource: YT.striver, problems: [
  ["684. Redundant Connection",3,"https://leetcode.com/problems/redundant-connection/"],
  ["200. Number of Islands",3,"https://leetcode.com/problems/number-of-islands/"],
  ["947. Most Stones Removed with Same Row or Column",3,"https://leetcode.com/problems/most-stones-removed-with-same-row-or-column/"],
  ["128. Longest Consecutive Sequence",3,"https://leetcode.com/problems/longest-consecutive-sequence/"],
  ["1970. Last Day Where You Can Still Cross",5,"https://leetcode.com/problems/last-day-where-you-can-still-cross/"],
  ["959. Regions Cut by Slashes",5,"https://leetcode.com/problems/regions-cut-by-slashes/"],
  ["721. Accounts Merge",3,"https://leetcode.com/problems/accounts-merge/"],
  ["924. Minimize Malware Spread",5,"https://leetcode.com/problems/minimize-malware-spread/"],
  ["1971. Find if Path Exists in Graph",1,"https://leetcode.com/problems/find-if-path-exists-in-graph/"],
  ["218. The Skyline Problem",5,"https://leetcode.com/problems/the-skyline-problem/"],
  ["839. Similar String Groups",5,"https://leetcode.com/problems/similar-string-groups/"],
  ["1168. Optimize Water Distribution in a Village",5,"https://leetcode.com/problems/optimize-water-distribution-in-a-village/"],
  ["305. Number of Islands II",5,"https://leetcode.com/problems/number-of-islands-ii/"],
  ["399. Evaluate Division",3,"https://leetcode.com/problems/evaluate-division/"]
]},
{ name: "Custom Data Structures", resource: YT.coderArmy, problems: [
  ["1146. Snapshot Array",3,"https://leetcode.com/problems/snapshot-array/"],
  ["981. Time Based Key-Value Store",3,"https://leetcode.com/problems/time-based-key-value-store/"],
  ["146. LRU Cache",3,"https://leetcode.com/problems/lru-cache/"],
  ["380. Insert Delete GetRandom O(1)",3,"https://leetcode.com/problems/insert-delete-getrandom-o1/"],
  ["155. Min Stack",3,"https://leetcode.com/problems/min-stack/"],
  ["715. Range Module",5,"https://leetcode.com/problems/range-module/"],
  ["244. Shortest Word Distance II",3,"https://leetcode.com/problems/shortest-word-distance-ii/"],
  ["705. Design HashSet",1,"https://leetcode.com/problems/design-hashset/"],
  ["716. Max Stack",5,"https://leetcode.com/problems/max-stack/"],
  ["346. Moving Average from Data Stream",1,"https://leetcode.com/problems/moving-average-from-data-stream/"],
  ["170. Two Sum III - Data structure design",1,"https://leetcode.com/problems/two-sum-iii-data-structure-design/"],
  ["303. Range Sum Query - Immutable",1,"https://leetcode.com/problems/range-sum-query-immutable/"],
  ["1032. Stream of Characters",5,"https://leetcode.com/problems/stream-of-characters/"],
  ["432. All O`one Data Structure",5,"https://leetcode.com/problems/all-oone-data-structure/"],
  ["1825. Finding MK Average",5,"https://leetcode.com/problems/finding-mk-average/"],
  ["460. LFU Cache",5,"https://leetcode.com/problems/lfu-cache/"]
]},
{ name: "Bitwise Manipulation", resource: YT.kunal, problems: [
  ["389. Find the Difference",1,"https://leetcode.com/problems/find-the-difference/"],
  ["1009. Complement of Base 10 Integer",1,"https://leetcode.com/problems/complement-of-base-10-integer/"],
  ["832. Flipping an Image",1,"https://leetcode.com/problems/flipping-an-image/"],
  ["136. Single Number",1,"https://leetcode.com/problems/single-number/"],
  ["137. Single Number II",3,"https://leetcode.com/problems/single-number-ii/"],
  ["271. Encode and Decode Strings",3,"https://leetcode.com/problems/encode-and-decode-strings/"],
  ["1863. Sum of All Subset XOR Totals",1,"https://leetcode.com/problems/sum-of-all-subset-xor-totals/"],
  ["1922. Find The K-th Lucky Number",3,"https://leetcode.com/problems/count-good-numbers/"],
  ["995. Minimum Number of K Consecutive Bit Flips",5,"https://leetcode.com/problems/minimum-number-of-k-consecutive-bit-flips/"],
  ["1371. Find the Longest Substring Having Vowels in Even Counts",3,"https://leetcode.com/problems/find-the-longest-substring-containing-vowels-in-even-counts/"],
  ["1442. Count Triplets That Can Form Two Arrays of Equal XOR",3,"https://leetcode.com/problems/count-triplets-that-can-form-two-arrays-of-equal-xor/"],
  ["2419. Longest Subarray With Maximum Bitwise AND",3,"https://leetcode.com/problems/longest-subarray-with-maximum-bitwise-and/"],
  ["1611. Minimum One Bit Operations to Make Integers Zero",5,"https://leetcode.com/problems/minimum-one-bit-operations-to-make-integers-zero/"],
  ["982. Triples with Bitwise AND Equal To Zero",5,"https://leetcode.com/problems/triples-with-bitwise-and-equal-to-zero/"],
  ["231. Power of Two",1,"https://leetcode.com/problems/power-of-two/"],
  ["190. Reverse Bits",1,"https://leetcode.com/problems/reverse-bits/"]
]},
{ name: "Math & Geometry", resource: YT.coderArmy, problems: [
  ["1232. Check If It Is a Straight Line",1,"https://leetcode.com/problems/check-if-it-is-a-straight-line/description/"],
  ["2481. Minimum Cuts to Divide a Circle",1,"https://leetcode.com/problems/minimum-cuts-to-divide-a-circle/description/"],
  ["836. Rectangle Overlap",1,"https://leetcode.com/problems/rectangle-overlap/description/"],
  ["1266. Minimum Time Visiting All Points",1,"https://leetcode.com/problems/minimum-time-visiting-all-points/description/"],
  ["7. Reverse Integer",3,"https://leetcode.com/problems/reverse-integer/description/"],
  ["593. Valid Square",3,"https://leetcode.com/problems/valid-square/description/"],
  ["223. Rectangle Area",3,"https://leetcode.com/problems/rectangle-area/description/"],
  ["939. Minimum Area Rectangle",3,"https://leetcode.com/problems/minimum-area-rectangle/description/"],
  ["3380. Maximum Area Rectangle With Point Constraints I",3,"https://leetcode.com/problems/maximum-area-rectangle-with-point-constraints-i/description/"],
  ["469. Convex Polygon",3,"https://leetcode.com/problems/convex-polygon/description/"],
  ["1828. Queries on Number of Points Inside a Circle",3,"https://leetcode.com/problems/queries-on-number-of-points-inside-a-circle/description/"],
  ["149. Max Points on a Line",5,"https://leetcode.com/problems/max-points-on-a-line/description/"],
  ["1610. Maximum Number of Visible Points",5,"https://leetcode.com/problems/maximum-number-of-visible-points/description/"],
  ["3102. Minimize Manhattan Distances",5,"https://leetcode.com/problems/minimize-manhattan-distances/description/"],
  ["335. Self Crossing",5,"https://leetcode.com/problems/self-crossing/description/"],
  ["587. Erect the Fence",5,"https://leetcode.com/problems/erect-the-fence/description/"],
  ["2152. Minimum Number of Lines to Cover Points",3,"https://leetcode.com/problems/minimum-number-of-lines-to-cover-points/description/"],
  ["878. Nth Magical Number",5,"https://leetcode.com/problems/nth-magical-number/description/"],
  ["2101. Detonate the Maximum Bombs",3,"https://leetcode.com/problems/detonate-the-maximum-bombs/description/"]
]},
{ name: "Extra Problems", resource: null, problems: [
  ["934. Shortest Bridge",3,"https://leetcode.com/problems/shortest-bridge/"],
  ["323. Number of Connected Components in an Undirected Graph",3,"https://leetcode.com/problems/number-of-connected-components-in-an-undirected-graph/"],
  ["4. Median of Two Sorted Arrays",5,"https://leetcode.com/problems/median-of-two-sorted-arrays/"],
  ["417. Pacific Atlantic Water Flow",3,"https://leetcode.com/problems/pacific-atlantic-water-flow/"],
  ["217. Contains Duplicate",1,"https://leetcode.com/problems/contains-duplicate/"],
  ["53. Maximum Subarray",3,"https://leetcode.com/problems/maximum-subarray/"],
  ["1. Two Sum",1,"https://leetcode.com/problems/two-sum/"],
  ["153. Find Minimum in Rotated Sorted Array",3,"https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/"],
  ["435. Non-overlapping Intervals",3,"https://leetcode.com/problems/non-overlapping-intervals/"],
  ["252. Meeting Rooms",1,"https://leetcode.com/problems/meeting-rooms/"],
  ["84. Largest Rectangle in Histogram",5,"https://leetcode.com/problems/largest-rectangle-in-histogram/"],
  ["572. Subtree of Another Tree",1,"https://leetcode.com/problems/subtree-of-another-tree/"],
  ["148. Sort List",3,"https://leetcode.com/problems/sort-list/"],
  ["191. Number of 1 Bits",1,"https://leetcode.com/problems/number-of-1-bits/"],
  ["11. Container with Most Water",3,"https://leetcode.com/problems/container-with-most-water/"],
  ["150. Evaluate Reverse Polish Notation",3,"https://leetcode.com/problems/evaluate-reverse-polish-notation/"],
  ["18. 4Sum",3,"https://leetcode.com/problems/4sum/"],
  ["851. Loud and Rich",3,"https://leetcode.com/problems/loud-and-rich/"],
  ["238. Product of Array Except Self",3,"https://leetcode.com/problems/product-of-array-except-self/"],
  ["300. Longest Increasing Subsequence",3,"https://leetcode.com/problems/longest-increasing-subsequence/"],
  ["371. Sum of Two Integers",3,"https://leetcode.com/problems/sum-of-two-integers/"],
  ["169. Majority Element",1,"https://leetcode.com/problems/majority-element/"],
  ["62. Unique Paths",3,"https://leetcode.com/problems/unique-paths/"],
  ["5. Longest Palindromic Substring",3,"https://leetcode.com/problems/longest-palindromic-substring/"],
  ["47. Permutations II",3,"https://leetcode.com/problems/permutations-ii/"],
  ["547. Number of Provinces",3,"https://leetcode.com/problems/number-of-provinces/"],
  ["142. Linked List Cycle II",3,"https://leetcode.com/problems/linked-list-cycle-ii/"],
  ["1888. Minimum Flips to Make the Binary String Alternate",3,"https://leetcode.com/problems/minimum-number-of-flips-to-make-the-binary-string-alternating/"],
  ["860. Lemonade Change",1,"https://leetcode.com/problems/lemonade-change/"],
  ["198. House Robber",3,"https://leetcode.com/problems/house-robber/"],
  ["448. Find All Numbers Disappeared in an Array",1,"https://leetcode.com/problems/find-all-numbers-disappeared-in-an-array/"],
  ["100. Same Tree",1,"https://leetcode.com/problems/same-tree/"],
  ["442. Find All Duplicates in an Array",3,"https://leetcode.com/problems/find-all-duplicates-in-an-array/"],
  ["588. Design In-Memory File System",5,"https://leetcode.com/problems/design-in-memory-file-system/"],
  ["1166. Design File System",3,"https://leetcode.com/problems/design-file-system/"],
  ["735. Asteroid Collision",3,"https://leetcode.com/problems/asteroid-collision/"],
  ["994. Rotting Oranges",3,"https://leetcode.com/problems/rotting-oranges/"],
  ["67. Add Binary",1,"https://leetcode.com/problems/add-binary/"],
  ["43. Multiply Strings",3,"https://leetcode.com/problems/multiply-strings/"],
  ["414. Third Maximum Number",1,"https://leetcode.com/problems/third-maximum-number/"],
  ["922. Sort Array By Parity II",1,"https://leetcode.com/problems/sort-array-by-parity-ii/"],
  ["905. Sort Array By Parity",1,"https://leetcode.com/problems/sort-array-by-parity/description/"]
]},
{ name: "Segment Trees", resource: YT.coderArmy, problems: [
  ["303. Range Sum Query - Immutable",1,"https://leetcode.com/problems/range-sum-query-immutable/description/"],
  ["307. Range Sum Query - Mutable",3,"https://leetcode.com/problems/range-sum-query-mutable/description/"],
  ["370. Range Addition",3,"https://leetcode.com/problems/range-addition/description/"],
  ["1094. Car Pooling",3,"https://leetcode.com/problems/car-pooling/description/"],
  ["699. Falling Squares",5,"https://leetcode.com/problems/falling-squares/description/"],
  ["732. My Calendar III",5,"https://leetcode.com/problems/my-calendar-iii/description/"],
  ["2736. Maximum Sum Queries",5,"https://leetcode.com/problems/maximum-sum-queries/description/"],
  ["308. Range Sum Query 2D - Mutable",3,"https://leetcode.com/problems/range-sum-query-2d-mutable/description/"],
  ["327. Count of Range Sum",5,"https://leetcode.com/problems/count-of-range-sum/description/"],
  ["2080. Range Frequency Queries",3,"https://leetcode.com/problems/range-frequency-queries/description/"],
  ["2407. Longest Increasing Subsequence II",5,"https://leetcode.com/problems/longest-increasing-subsequence-ii/description/"]
]},
{ name: "Prefix Sum", resource: YT.coderArmy, problems: [
  ["1480. Running Sum of 1d Array",1,"https://leetcode.com/problems/running-sum-of-1d-array/"],
  ["303. Range Sum Query - Immutable",1,"https://leetcode.com/problems/range-sum-query-immutable/"],
  ["560. Subarray Sum Equals K",3,"https://leetcode.com/problems/subarray-sum-equals-k/"],
  ["1310. XOR Queries of a Subarray",3,"https://leetcode.com/problems/xor-queries-of-a-subarray/"],
  ["2559. Count Vowel Strings in Ranges",3,"https://leetcode.com/problems/count-vowel-strings-in-ranges/"],
  ["325. Maximum Size Subarray Sum Equals k",3,"https://leetcode.com/problems/maximum-size-subarray-sum-equals-k/"],
  ["1248. Count Number of Nice Subarrays",3,"https://leetcode.com/problems/count-number-of-nice-subarrays/"],
  ["930. Binary Subarrays With Sum",3,"https://leetcode.com/problems/binary-subarrays-with-sum/"],
  ["2364. Count Number of Bad Pairs",3,"https://leetcode.com/problems/count-number-of-bad-pairs/"],
  ["1658. Minimum Operations to Reduce X to Zero",3,"https://leetcode.com/problems/minimum-operations-to-reduce-x-to-zero/"],
  ["974. Subarray Sums Divisible by K",3,"https://leetcode.com/problems/subarray-sums-divisible-by-k/"],
  ["1497. Check If Array Pairs Are Divisible by k",3,"https://leetcode.com/problems/check-if-array-pairs-are-divisible-by-k/"],
  ["1590. Make Sum Divisible by P",3,"https://leetcode.com/problems/make-sum-divisible-by-p/"],
  ["523. Continuous Subarray Sum",3,"https://leetcode.com/problems/continuous-subarray-sum/"],
  ["2575. Find the Divisibility Array of a String",3,"https://leetcode.com/problems/find-the-divisibility-array-of-a-string/"],
  ["2845. Count of Interesting Subarrays",3,"https://leetcode.com/problems/count-of-interesting-subarrays/"],
  ["1442. Count Triplets That Can Form Two Arrays of Equal XOR",3,"https://leetcode.com/problems/count-triplets-that-can-form-two-arrays-of-equal-xor/"],
  ["1915. Number of Wonderful Substrings",3,"https://leetcode.com/problems/number-of-wonderful-substrings/"],
  ["1542. Find Longest Awesome Substring",3,"https://leetcode.com/problems/find-longest-awesome-substring/"],
  ["1371. Find the Longest Substring Containing Vowels in Even Counts",3,"https://leetcode.com/problems/find-the-longest-substring-containing-vowels-in-even-counts/"],
  ["304. Range Sum Query 2D - Immutable",3,"https://leetcode.com/problems/range-sum-query-2d-immutable/"],
  ["1314. Matrix Block Sum",3,"https://leetcode.com/problems/matrix-block-sum/"],
  ["2132. Stamping the Grid",5,"https://leetcode.com/problems/stamping-the-grid/"],
  ["221. Maximal Square",3,"https://leetcode.com/problems/maximal-square/"],
  ["2201. Count Artifacts That Can Be Extracted",3,"https://leetcode.com/problems/count-artifacts-that-can-be-extracted/"],
  ["3148. Maximum Difference Score in a Grid",3,"https://leetcode.com/problems/maximum-difference-score-in-a-grid/"],
  ["2017. Grid Game",3,"https://leetcode.com/problems/grid-game/"]
]}
];
